version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ../database/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ../healthscripts/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai_nssf:
        container_name: "oai-nssf"
        image: oaisoftwarealliance/oai-nssf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./slicing_base_config.yaml:/openair-nssf/etc/config.yaml
            - ./nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai_udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./slicing_base_config.yaml:/openair-udr/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.70.133
    oai_udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./slicing_base_config.yaml:/openair-udm/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_udr
        networks:
            public_net:
                ipv4_address: 192.168.70.134
    oai_ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./slicing_base_config.yaml:/openair-ausf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_udm
        networks:
            public_net:
                ipv4_address: 192.168.70.135
    oai_nrf_slice12:
        container_name: "oai-nrf-slice12"
        image: oaisoftwarealliance/oai-nrf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./slicing_slice1_config.yaml:/openair-nrf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    # oai_nrf_slice3:
    #     container_name: "oai-nrf-slice3"
    #     image: oaisoftwarealliance/oai-nrf:v2.1.0
    #     expose:
    #         - 80/tcp
    #         - 8080/tcp
    #     volumes:
    #         - ./conf/slicing_slice3_config.yaml:/openair-nrf/etc/config.yaml
    #     networks:
    #         public_net:
    #             ipv4_address: 192.168.70.137
    oai_amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./slicing_base_config.yaml:/openair-amf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice12
            # - oai_nrf_slice3
            - oai_ausf
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai_smf_slice1:
        container_name: "oai-smf-slice1"
        image: oaisoftwarealliance/oai-smf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./slicing_slice1_config.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.139
        extra_hosts:
            - "oai-upf-slice1:192.168.70.129"
    oai_smf_slice2:
        container_name: "oai-smf-slice2"
        image: oaisoftwarealliance/oai-smf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./slicing_slice2_config.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.140
    oai_upf_slice1:
        container_name: "oai-upf-slice1"
        image: oaisoftwarealliance/oai-upf:v2.1.0
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./slicing_slice1_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice12
            - oai_smf_slice1
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        network_mode: host
        extra_hosts:
            - "oai-ext-dn:192.168.72.145"
            - "oai-nrf-slice12:192.168.70.136"
    oai_upf_slice2:
        container_name: "oai-upf-slice2"
        image: oaisoftwarealliance/oai-upf:v2.1.0
        expose:
            - 2152/udp
            - 8805/udp
            # - 8080/tcp
        volumes:
            - ./slicing_slice2_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice12
            - oai_smf_slice2
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.143
    oai_ext_dn:
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        privileged: true
        init: true
        container_name: oai-ext-dn
        environment:
            - EBPF_GW_SETUP=yes
            - EBPF_GW_N6_IP_ADDR=192.168.72.145
            - GW_SGI_IP_ADDR=192.168.70.145
            - GW_N3_IP_ADDR=192.168.71.145
            - UE_IP_ADDRESS_POOL=12.1.1.0/24
            - N6_UPF_IP_ADDR=192.168.72.129
            - SGI_DEMO_OAI_ADDR=192.168.70.129
        entrypoint: /bin/bash -c \
            "/tmp/trfgen_entrypoint.sh; \
            iptables -t nat -A POSTROUTING -o eth2 -s 12.1.2.0/24 -j SNAT --to-source 192.168.70.145; \
            ip route add 12.1.2.0/24 via 192.168.70.143; ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "ip r | grep 12.1"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.145
            n3_net:
                ipv4_address: 192.168.71.145
            n6_net:
                ipv4_address: 192.168.72.145
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    n3_net:
        driver: bridge
        name: demo-oai-n3-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n3"
    n6_net:
        driver: bridge
        name: demo-oai-n6-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n6"
