version: '3'
services:
  mqtt_broker:
    container_name: Warehouse_MQTT_Broker
    image: eclipse-mosquitto:2.0.18
    restart: always
    ports:
      - 1883:1883
      - 9002:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf