defaults: &defaults
  speed: 1  # Default speed of the AGVs
  cell_distance: 1  # Default cell distance between two cells
  direction: "N"  # Default initial direction of the AGVs
  turning_time: 1  # Default time taken to turn the AGVs
  grid_path: "grid.xlsx"  # Default file path of the warehouse map

instances:
  - port: 5001
    AGV_ID: 1
    current_location: [15, 12]
    <<: *defaults  # Merges default values here

  - port: 5002
    AGV_ID: 2
    current_location: [14, 1]
    <<: *defaults  # Merges default values here

  # Add more instances as needed
